<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-KJ4U1G6" name="org.br.test.CheckoutPageTest" tests="6" failures="1" timestamp="14 Jan 2020 06:33:48 GMT" time="5.953" errors="0">
  <testcase name="productDetailActualTest" time="0.112" classname="org.br.test.CheckoutPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	product detail mismatch expected [M] but found [Size: M]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
product detail mismatch expected [M] but found [Size: M]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.br.test.CheckoutPageTest.productDetailActualTest(CheckoutPageTest.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- productDetailActualTest -->
  <testcase name="orderSummaryTest" time="0.054" classname="org.br.test.CheckoutPageTest"/>
  <testcase name="guestUserDisplayTest" time="0.235" classname="org.br.test.CheckoutPageTest"/>
  <testcase name="returnUserDisplayTest" time="1.433" classname="org.br.test.CheckoutPageTest"/>
  <testcase name="loginReturnUserTest" time="0.668" classname="org.br.test.CheckoutPageTest"/>
  <testcase name="getTitles" time="3.451" classname="org.br.test.CheckoutPageTest"/>
</testsuite> <!-- org.br.test.CheckoutPageTest -->
